### ISSUE TITLE
Cannot install ray on Python 3.9.2

### ISSUE THREAD

**Issue by hsm207** [DerwenAI/ray_tutorial#12]
I created a container based on the [python:3.9-buster](https://hub.docker.com/layers/python/library/python/3.9.2-buster/images/sha256-c3f2c7d196f80674af8778625e03584867dcea9911885c99feb976b4bb7fc49a?context=explore) image to run the notebooks.

After cloning the repo into the container and moving to the repo's root folder, I ran the following commands:

```bash
python -m venv venv
source venv/bin/activate
python3 -m pip install -U pip
python3 -m pip install -r requirements.txt
```

The last command threw the following error:

```
ERROR: Could not find a version that satisfies the requirement ray>=1.2
ERROR: No matching distribution found for ray>=1.2
```

Using the python:3.7-buster and python:3.8-buster image which comes with python 3.7.10 and python 3.8.9 respectively works fine.

**Comment by ceteri** [comment]
Thank you @hsm207 this is an important issue to catch.

Python 3.9 was begin supported, however the PR got reverted due to installation conflicts in some of the dependencies. There is discussion about this issue at <https://github.com/ray-project/ray/pull/12613>

I've just updated the `README.md` to note this constraint, that only Py 3.6 through 3.8 are supported for this tutorial.

**Comment by hsm207** [comment]
@ceteri thanks for sharing more details about the Python 3.9 support on Ray.

I noticed the PR you linked to has been merged so I tried this:

```
pip install https://s3-us-west-2.amazonaws.com/ray-wheels/latest/ray-2.0.0.dev0-cp39-cp39-manylinux2014_x86_64.whl
pip install -r requirements.txt 
pip install setproctitle
```
The notebooks run fine now
